Bootstrap: docker
From: nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04

Stage: spython-base

%post

LANG=C.UTF-8
LC_ALL=C.UTF-8

DEBIAN_FRONTEND=noninteractive && apt-get update --fix-missing && apt-get install -y \
libopencolorio-dev \
libboost-all-dev \
libturbojpeg0-dev \
libopenjp2-7-dev \
libjpeg-dev \
libtiff-dev \
libpng-dev

%environment
export LANG=C.UTF-8
export LC_ALL=C.UTF-8
export PATH=/opt/conda/bin:$PATH
export PATH=/opt/conda/envs/pytorch/bin:$PATH
%runscript
exec /bin/bash "$@"
%startscript
exec /bin/bash "$@"

